"""empty message

Revision ID: 2747a3fc4850
Revises: fac6c2536b95
Create Date: 2026-04-28 18:12:06.629262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2747a3fc4850'
down_revision = 'fac6c2536b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
