"""empty message

Revision ID: 441726df2a1a
Revises: 2c8a8377a204
Create Date: 2026-04-23 18:50:35.751258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441726df2a1a'
down_revision = '2c8a8377a204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
