"""Add is_read to Chat model nullable

Revision ID: 67532a2a4231
Revises: aff81ad1f3da
Create Date: 2026-04-28 12:34:28.934963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67532a2a4231'
down_revision = 'aff81ad1f3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
