"""Add created_at to Chat

Revision ID: aff81ad1f3da
Revises: c242b0c3d1b9
Create Date: 2026-04-27 12:56:31.632415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff81ad1f3da'
down_revision = 'c242b0c3d1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
