"""remove redundant time columns from place

Revision ID: b65abeca9a47
Revises: 2ebe5d895040
Create Date: 2026-05-04 16:57:05.153390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65abeca9a47'
down_revision = '2ebe5d895040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))

    # ### end Alembic commands ###
