"""empty message

Revision ID: c242b0c3d1b9
Revises: 0bc39a1b3194
Create Date: 2026-04-24 19:51:06.892843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c242b0c3d1b9'
down_revision = '0bc39a1b3194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('race_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('race_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
