"""Add start_time and end_time to Place model

Revision ID: e31de4c0ed88
Revises: 010f096787cc
Create Date: 2026-04-29 11:25:31.076148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31de4c0ed88'
down_revision = '010f096787cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_type', sa.String(length=120), nullable=True))
        batch_op.alter_column('animal_type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('dog', 'cat', 'other', name='pet_animal_type'),
               existing_nullable=False)
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('small', 'medium', 'large', name='pet_size'),
               existing_nullable=False)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.Enum('small', 'medium', 'large', name='pet_size'),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('animal_type',
               existing_type=sa.Enum('dog', 'cat', 'other', name='pet_animal_type'),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('other_type')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
