"""empty message

Revision ID: f82217b6a3e7
Revises: f735fd986287
Create Date: 2026-05-02 05:02:20.460163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82217b6a3e7'
down_revision = 'f735fd986287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity_people', sa.Integer(), nullable=False),
    sa.Column('capacity_pets', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tables', ['table_id'], ['id'])
        batch_op.create_foreign_key(None, 'pets', ['pet_id'], ['id'])
        # batch_op.drop_column('pet_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('table_id')
        batch_op.drop_column('pet_id')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('address')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('is_read')
        batch_op.drop_column('created_at')

    op.drop_table('tables')
    op.drop_table('place_schedules')
    # ### end Alembic commands ###
