cities = [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Malaga",
    "Murcia",
    "Palma",
    "Las Palmas de Gran Canaria",
    "Bilbao",
    "Alicante",
    "Cordoba",
    "Valladolid",
    "Vigo",
    "Gijon",
    "Hospitalet de Llobregat",
    "A Coruna",
    "Vitoria-Gasteiz",
    "Granada",
    "Elche",
    "Oviedo",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez de la Frontera",
    "Sabadell",
    "Mostoles",
    "Santa Cruz de Tenerife",
    "Pamplona",
    "Almeria",
]
